# Generated by Django 3.2 on 2023-05-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20230527_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlead',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.staff'),
        ),
    ]
