# Generated by Django 3.2 on 2023-05-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20230529_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectlead',
            old_name='staff',
            new_name='project_lead',
        ),
    ]
