# Generated by Django 3.2 on 2023-06-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_staff_projectlead_project_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created', 'updated', 'name'], 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.RemoveField(
            model_name='projectlead',
            name='project_lead',
        ),
        migrations.AddField(
            model_name='projectlead',
            name='project_leads',
            field=models.ManyToManyField(blank=True, null=True, to='website.Staff'),
        ),
    ]
