# Generated by Django 3.2 on 2023-06-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20230613_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlead',
            name='slug',
        ),
        migrations.AlterField(
            model_name='projectlead',
            name='project_leads',
            field=models.ManyToManyField(blank=True, to='website.Staff'),
        ),
    ]
