# Generated by Django 3.2 on 2023-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20230613_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlead',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectlead',
            name='project_leads',
            field=models.ManyToManyField(blank=True, null=True, to='website.Staff'),
        ),
    ]
