# Generated by Django 3.2 on 2023-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20230613_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email_1',
            new_name='alt_email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='mobile_1',
            new_name='alt_mobile',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='email_2',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='mobile_2',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='projectlead',
            name='project_leads',
            field=models.ManyToManyField(blank=True, to='website.Staff'),
        ),
    ]
