# Generated by Django 3.2 on 2023-06-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20230613_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='department',
        ),
        migrations.AddField(
            model_name='management',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.section'),
        ),
    ]
