# Generated by Django 3.2 on 2023-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20230613_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlead',
            options={'ordering': ['project'], 'verbose_name_plural': 'Project Leads'},
        ),
        migrations.RemoveField(
            model_name='projectlead',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectlead',
            name='slug',
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=3400.0, max_digits=128, null=True),
        ),
    ]
