# Generated by Django 3.2 on 2023-11-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20231128_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost',
        ),
    ]
