# Generated by Django 3.2 on 2023-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_project_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=3400.0, max_digits=9, null=True),
        ),
    ]
