# Generated by Django 3.2 on 2023-11-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_project_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='section',
        ),
        migrations.AddField(
            model_name='management',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.department'),
        ),
    ]
