# Generated by Django 3.2 on 2023-11-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20231128_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['person'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
