# Generated by Django 3.2 on 2023-11-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_project_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
