# Generated by Django 3.2 on 2023-12-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_project_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlead',
            options={'ordering': ['staff'], 'verbose_name_plural': 'Project Leads'},
        ),
        migrations.RemoveField(
            model_name='projectlead',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectlead',
            name='project_leads',
        ),
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.ManyToManyField(blank=True, null=True, to='website.ProjectLead'),
        ),
        migrations.AddField(
            model_name='projectlead',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.staff'),
        ),
    ]
