# Generated by Django 3.2 on 2023-12-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20231201_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlead',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
