# Generated by Django 3.2 on 2023-12-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_projectlead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlead',
            name='name',
            field=models.CharField(default='Tree', max_length=256),
        ),
    ]
