# Generated by Django 3.2 on 2023-12-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20231201_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlead',
            name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='lead',
            field=models.ManyToManyField(to='website.ProjectLead'),
        ),
    ]
