# Generated by Django 3.2 on 2023-12-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20231201_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='lead',
            new_name='leads',
        ),
        migrations.AddField(
            model_name='boardofdirector',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='management',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
