# Generated by Django 3.2 on 2023-12-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20231203_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectoverview',
            old_name='description',
            new_name='overview',
        ),
    ]
