# Generated by Django 3.2 on 2023-12-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_rename_description_projectoverview_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectoverview',
            name='overview',
            field=models.TextField(default='Project Overview', max_length=512),
        ),
        migrations.CreateModel(
            name='ProjectConcept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concept', models.TextField(default='Project Concept...', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
    ]
