# Generated by Django 3.2 on 2023-12-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20231203_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDesign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('design', models.TextField(default='Project Design...', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectConstruction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('construction', models.TextField(default='Project Construction...', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
    ]
