# Generated by Django 3.2 on 2023-12-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_projectconstruction_projectdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardofdirector',
            name='dateOfLasttAppointment',
            field=models.DateField(blank=True, null=True, verbose_name='date of First Appointment'),
        ),
    ]
