# Generated by Django 3.2 on 2023-12-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_boardofdirector_dateoflasttappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='dateOfLasttAppointment',
            field=models.DateField(blank=True, null=True, verbose_name='date of Last Appointment'),
        ),
        migrations.AlterField(
            model_name='boardofdirector',
            name='dateOfLasttAppointment',
            field=models.DateField(blank=True, null=True, verbose_name='date of Last Appointment'),
        ),
    ]
