# Generated by Django 3.2 on 2023-12-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20231226_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
